# Generated by Django 4.0.3 on 2023-08-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_question_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
